DROP TABLE IF EXISTS auth_session;
DROP TABLE IF EXISTS llm_request_record;
DROP TABLE IF EXISTS app_user;

CREATE TABLE app_user (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(64) NOT NULL UNIQUE,
    password_hash VARCHAR(100) NOT NULL,
    display_name VARCHAR(64) NOT NULL,
    status VARCHAR(16) NOT NULL,
    role VARCHAR(16) NOT NULL DEFAULT 'USER',
    created_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE auth_session (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    token_hash CHAR(64) NOT NULL UNIQUE,
    expires_at TIMESTAMP(3) NOT NULL,
    created_at TIMESTAMP(3) NOT NULL,
    last_used_at TIMESTAMP(3) NOT NULL,
    revoked_at TIMESTAMP(3),
    CONSTRAINT fk_auth_session_user
        FOREIGN KEY (user_id) REFERENCES app_user (id) ON DELETE CASCADE
);

CREATE TABLE llm_request_record (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT,
    request_id VARCHAR(64) NOT NULL UNIQUE,
    provider VARCHAR(32) NOT NULL,
    model VARCHAR(128) NOT NULL,
    result_status VARCHAR(16) NOT NULL,
    prompt_tokens INTEGER,
    completion_tokens INTEGER,
    total_tokens INTEGER,
    latency_ms BIGINT NOT NULL,
    upstream_status_code SMALLINT,
    error_code VARCHAR(64),
    error_message VARCHAR(512),
    requested_at TIMESTAMP(3) NOT NULL,
    CONSTRAINT fk_llm_request_record_user
        FOREIGN KEY (user_id) REFERENCES app_user (id)
);
