DROP TABLE IF EXISTS app_credential;

CREATE TABLE app_credential (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    app_id VARCHAR(64) NOT NULL UNIQUE,
    app_name VARCHAR(128) NOT NULL,
    api_key_hash VARCHAR(64) NOT NULL UNIQUE,
    status VARCHAR(16) NOT NULL,
    rate_limit_per_minute INTEGER NOT NULL,
    daily_token_quota BIGINT NOT NULL,
    allowed_model_aliases VARCHAR(1024),
    created_at TIMESTAMP(3) NOT NULL,
    updated_at TIMESTAMP(3) NOT NULL
);
