DROP TABLE IF EXISTS llm_request_record;

CREATE TABLE llm_request_record (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    request_id VARCHAR(64) NOT NULL UNIQUE,
    provider VARCHAR(32) NOT NULL,
    model VARCHAR(128) NOT NULL,
    result_status VARCHAR(16) NOT NULL,
    prompt_tokens INTEGER,
    completion_tokens INTEGER,
    total_tokens INTEGER,
    latency_ms BIGINT NOT NULL,
    upstream_status_code SMALLINT,
    error_code VARCHAR(64),
    error_message VARCHAR(512),
    requested_at TIMESTAMP(3) NOT NULL
);
